/*

 MIT License

 Copyright (c) 2022 Looker Data Sciences, Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 */
import React, { useContext } from 'react'
import { ComponentsProvider } from '@looker/components'
import { ExtensionContext40 } from '@looker/extension-sdk-react'
import { MountPoint } from '@looker/extension-sdk'
import { VisualizationTile } from './components/VisualizationTile/VisualizationTile'
import { DashboardTile } from './components/DashboardTile/DashboardTile'

const getDefaultRouteComponent = (mountPoint) => {
  if (mountPoint === MountPoint.dashboardVisualization) {
    return <VisualizationTile />
  }
  if (mountPoint === MountPoint.dashboardTile) {
    return <DashboardTile />
  }
  // Standalone extensions do not get the additional CSS
  // that ensures the container div occupies 100% of the
  // IFRAME content window.
  return <DashboardTile standalone={true} />
}

export const TileExtension = () => {
  const { lookerHostData } = useContext(ExtensionContext40)

  // The additional CSS generated for dashboard tiles and
  // visualizations assumes that ComponentsProvider is the first
  // component in the tree. ExtensionProvider40 can be ignored
  // as it does not generated any HTML. If you do need to insert
  // HTML in the tree before ComponentsProvider you will need to
  // generate CSS that ensures the div generated by components
  // provider gets a height of 100%.
  return (
    <ComponentsProvider>
      {getDefaultRouteComponent(lookerHostData?.mountPoint)}
    </ComponentsProvider>
  )
}
